version: '3.7'

services:
  django_gunicorn:
    container_name: django_gunicorn
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"  # This can be internal only; Nginx will handle external requests
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://attendence:k^OSf)$I9x%*@postgres:5432/attendence
    restart: always

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static:/static
      - ./path/to/certificates:/etc/letsencrypt  # Mount the directory with your SSL certificates
    ports:
      - "8080:80"
      - "443:443"  # Expose port 443 for HTTPS traffic
    depends_on:
      - django_gunicorn
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=attendence
      - POSTGRES_USER=attendence
      - POSTGRES_PASSWORD=k^OSf)$I9x%*
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  static:
  pgdata: