# Generated by Django 5.0.6 on 2024-09-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
